name: Transitstat post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint main_circulator.py main_connector.py src tests
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 main_circulator.py main_connector.py src tests
      - name: Look for security issues with Bandit
        run: |
          bandit main_circulator.py main_connector.py src tests
      - name: Type checking
        run: |
          mypy main_circulator.py main_connector.py src tests
      - name: Pytest
        run: |
          pytest
