name: Transitstat post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Build ridesystems wheel
        uses: actions/checkout@v2
        with:
          repository: city-of-baltimore/ridesystems
          path: ridesystems
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip pylint flake8 bandit mypy wheel ./ridesystems
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint python
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 python
      - name: Look for security issues with Bandit
        run: |
          bandit python
      - name: Type checking
        run: |
          mypy python
